const images = {
  celebrate: require('./celebrate.png'),
  diamond: require('./diamond.png'),
  arrowBack: require('./arrowBack.png'),
  eye: require('./eye.png'),
  eyeEnable: require('./eyeEnable.png'),
  facebook: require('./facebook.png'),
  google: require('./google.png'),
  apple: require('./apple-logo.png'),
  checkBoxFilled: require('./checkboxfilled.png'),
  checkBoxEmpty: require('./emptyCheckBox.png'),
  room: require('./room.png'),
  splashBg: require('./splashBg.png'),
  logowithTagline: require('./logowithTagline.png'),
  onboarding1: require('./onboarding1.gif'),
  onboarding2: require('./onboarding2.gif'),
  onboarding3: require('./onboarding3.gif'),
  socialSignUp: require('./socialSignUp.gif'),
  email: require('./email.png'),
  startJourney: require('./startJourney.png'),
  singleRoom: require('./signleRoom.png'),
  sharedRoom: require('./sharedRoom.png'),
  house: require('./house.png'),
  building: require('./building.png'),
  forest: require('./forest.png'),
  search: require('./search.png'),
  mapPin: require('./mapPin.png'),
  locationIcon: require('./locationIcon.png'),
  calender: require('./calender.png'),
  outdoor: require('./outdoor.png'),
  biking: require('./biking.png'),
  museums: require('./museums.png'),
  food: require('./food.png'),
  culturalCenters: require('./culturalCenters.png'),
  bars: require('./bars.png'),
  addPropertyIcon: require('./addPropertyIcon.png'),
  cardImage: require('./cardImage.png'),
  calenderOrange: require('./calenderOrange.png'),
  roomIcon: require('./roomIcon.png'),
  personIcon: require('./personIcon.png'),
  location: require('./location.png'),
  smallCardImage: require('./smallCardImage.png'),
  userImage: require('./userImage.png'),
  cross: require('./cross.png'),
  camera: require('./camera.png'),
  gallery: require('./gallery.png'),
  backArrowIcon: require('./backArrowIcon.png'),
  glob: require('./globe.png'),
  exchange: require('./exchange.png'),
  message: require('./messenger.png'),
  profile: require('./user.png'),
  notification: require('./notification.png'),
  userProfile: require('./userProfile.jpeg'),
  exchange_calender: require('./calendar_exchange.png'),
  date: require('./date.png'),
  map_location: require('./map_location.png'),
  rooms: require('./rooms.png'),
  profileBg: require('./profileBg.png'),
  settings: require('./setting.png'),
  rightArrow: require('./rightArrow.png'),
  lock: require('./lock.png'),
  help: require('./help.png'),
  document: require('./document.png'),
  cameraIcon: require('./cameraIcon.png'),
  cancel: require('./cancel.png'),
  connectionSentIcon: require('./connectionSentIcon.gif'),
  avatar: require('./avatar.gif'),
  sendIcon: require('./send.png'),
  moreOptions: require('./moreOptions.png'),
  noMessages: require('./noMessages.png'),
  radioSelected: require('./radioSelected.png'),
  radioUnSelected: require('./radioUnSelected.png'),
  logout: require('./logout.png'),
  video1: require('./video1.png'),
  video2: require('./video2.png'),
  galleryImage1: require('./galleryImage1.png'),
  galleryImage2: require('./galleryImage2.png'),
  galleryImage3: require('./galleryImage3.png'),
  playIcon: require('./playButton.png'),
  play: require('./play.png'),
  passwordUpdated: require('./passwordUpdated.gif'),
  appLogo: require('./applogo.png'),
  splash: require('./splash_gif.gif'),
  imagePlaceHolder: require('./productDetailsImag.png'),
  africa:require("./africa.png"),
  antarctica:require("./Antarctica.png"),
  asia:require("./asia.png"),
  northAmerica:require("./northAmerica.png"),
  southAmerica:require("./southAmerica.png"),
  chat:require("./chat.png"),
  edit:require("./edit.png"),
  secure:require("./secure.png"),
  user:require("./user.png"),
  attachment:require("./attachment.png"),
  arrow_down:require("./arrow_down.png"),
  success:require("./success.png"),
  three_dots:require("./three_dots.png"),
  start_rating:require("./star_rating.png"),
  three_menu:require("./three_menu.png"),


};

export default images;
