const Extensions = {
  IMAGE: [
    'png',
    '.png',
    'jpg',
    '.jpg',
    'jpeg',
    '.jpeg',
    'tiff',
    '.tiff',
    'image/png',
    'image/jpg',
    'image/jpeg',
    'image/tiff',
  ],
  PDF: ['pdf', '.pdf', 'application/pdf'],
  VIDEO: ['mp4', '.mp4', 'video/mp4', 'video/quicktime'],
  TEXT: ['txt', '.txt'],
  DOCS: [
    'pptx',
    '.pptx',
    'ppt',
    '.ppt',
    'pptm',
    '.pptm',
    'docx',
    '.docx',
    'doc',
    '.doc',
    'docs',
    '.docs',
    'xls',
    '.xls',
    'xlsm',
    '.xlsm',
    'xlsb',
    '.xlsb',
    'xlsx',
    '.xlsx',
  ],
  WORD: ['docx', '.docx', 'doc', '.doc', 'docs', '.docs'],
  EXCEL: ['xls', '.xls', 'xlsm', '.xlsm', 'xlsb', '.xlsb', 'xlsx', '.xlsx'],
  POWER_POINT: ['pptx', '.pptx', 'ppt', '.ppt', 'pptm', '.pptm'],
};

export {Extensions};
