export const ScreenTitle = {
  HOME: 'Explore',
  EXCHANGES: 'Exchanges',
  MESSAGE: 'Message',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  NOTIFICATION_SETTINGS: 'Notification Settings',
  PRIVACY_POLICY: 'Privacy Policy',
  EDIT_PROFILE: 'Edit Profile',
  NOTIFICATIONS: 'Notifications',
  INTRO_VIDEOS: 'Intro Videos',
  IMAGE_GALLERY: 'Image Gallery',
  Change_Schedule: 'Change Schedule',
  FRIENDS: 'Friends',
  EDIT_LISTING: "Edit Listing",
  REFFERS: "Referrer",
  CLIENTS:"Clients",
  ADD_CLIENTS:"Add Client",
  My_COMMISSIONS:"My Commission",
};
